apiVersion: v1
kind: Secret
metadata:
    name: gitlab-auth
    namespace: apps
stringData:
    password: ENC[AES256_GCM,data:TGLFqIk5KBL2uNW/TZHQhYnzW8SzGclgLTI=,iv:9on3vhRQBS/caGrKmh9anwMFZE/RjgBeCL9+1tNEj4A=,tag:PBuXpgik45FHpb1Ga2gqhA==,type:str]
    username: ENC[AES256_GCM,data:qSWJtK4oLmkq6vXNFUvTd5+u,iv:ZZRXLXS5vQ5zMcZdSFH4TJNJxHPUg5DTSdB9I0x4uI8=,tag:poSQQ45wKn3Cmg0qWOnEwg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-08-28T21:17:37Z"
    mac: ENC[AES256_GCM,data:vA4OVLDZUFN3/qZ9DS65hWNSmJH23ETJdFKVXOAGRfjySVoJiw+KbEJx+tH1MyYG3iAg2qK9U2oPos9ZTca4jYCB2Mzn5LHRolQ3q7zy1t90yxPGFzvW5rji2Xe/uNOVJ8k6PsEhMvqtILeX+Z4764VMxcpnuwY0wgQD3ic5AoM=,iv:DYndZukseTC9/aV9IULsR8TgocaWKpljC1E2tWckNvY=,tag:OH9+ZipdipyCUBpcUy5IyQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
