apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: dev
  namespace: apps
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: gitlab-auth
  url: https://gitlab.com/abohmeed/weatherappstaging.git
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: gitlab
  namespace: apps
spec:
  type: oci
  interval: 5m0s
  url: oci://registry.gitlab.com/abohmeed/weatherappstaging
  secretRef:
    name: gitlab-auth
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dev
  namespace: apps
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-hcvault
  interval: 1m0s
  path: ./
  prune: true
  serviceAccountName: dev
  sourceRef:
    kind: GitRepository
    name: dev
---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-auth
  namespace: apps
stringData:
  password: ENC[AES256_GCM,data:60LuXUqRCX0e80s5F491FdcZA+pFk3gjULg=,iv:KRwLmw6R6DMCI9KTRB0w3ZzV4dJALeCXtBV9s9VPrfE=,tag:S7f5Cz9ZCjcdVlEFF/Zrtw==,type:str]
  username: ENC[AES256_GCM,data:Yc4Yqo/lQTBLtQkp7zJ56ydk,iv:JeYZReKe3MJS69a0IXtv23oFlv/VegVYKSHxbCDtcAo=,tag:LkNSfBa0Ek3UX91BkkIedA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: "2023-10-29T13:08:44Z"
  mac: ENC[AES256_GCM,data:OKZpvux6JhPptiDItD9xCjoffsM6h7BwCliB/gYlgcwdxAlS7RL/sCPsp3KhLvsZ5rB2u/e4U3kdr1nreYc3brPM/kImCML34uTpypHGJxm9Zd9IXVMrYwuq2FoQ3EmYA8jraG+haJk/0L6qZZPiHK0unLKVBKw/FwMrO7BnpYg=,iv:ySdKlYL80WUOTPggjbi5z03GKYaCM20lZRfgjKfmTvo=,tag:cnP0+oriquffe4BYN5ypcQ==,type:str]
  pgp:
  - created_at: "2023-10-29T13:08:44Z"
    enc: |-
      -----BEGIN PGP MESSAGE-----

      hQIMA5l1N71aLET8ARAAmhnngmKZ4byVXCZV4M1DRo+jR49Jh9HDqSkz4XBqg+E9
      kUcdRrKz354/eBBMez3TH3DN1Ubw4TsihRyYHoDc0LpK6kybZt3f1SOXYWOT2HB2
      iEfLne/5/NFGc/5yBNjEC8oREz7KHPCV6SzMassjgp83/cu9HO63JLEPZwAfKeUt
      Bc3Cn11Ks89MezCfN1kwN54S5CzMR/48e0Ix/jnPho9exkL7j7TuDvwK2CJOryYX
      Dd7u9hzlJrhyJrnJL5cl3lMk/VWul42WfscpX3VesDs99N67a71Tjh1sgv1nWxgX
      D3JMkPxPw4+A88rBbxFQBIujz7fh1VHoACQUEorYNIQ+SXvvJxOwMrn1R2qf8c0h
      5abIqqSSzO9HZKDDrbN33nmBiQYKquGLLpY4veNo/p+WiI+krwaAc10kDbSTiYCU
      9vv2r3rvKq6IFzvbYslB1ZM7xH7Ijq/8b+EiGi5F18Hi53qVRbXk9KVIEaCMqhKg
      bsR9Cyj0iZ1wtMf9XdY1J61OZBKRNyisZAprBIuBiB0BdKiKY3MruaTi0+Acv0HW
      M5bpmztHj9sqMRBFahs1Rh+rQRrCZ8QO2n6zgLOYSB7qXRIA1pYF7bkUmEcC9684
      aGBrzJ/cxCvkG4SlosbjIOAai6yxcMHtJeeBslTaffEg/qU928X1ma/YUlmUlpDU
      ZgEJAhCLOiX1VcNIIYAn9IQHDuEVDBF61VRoCjNTVcrXuKdhIPhzrUGry1rPgHoz
      TKwO5h0GnW6ZAZyt/q6mx+Tgy+QA+v45BnTXcxfwcvwGF6SI/H49h1uHD5HAEw2O
      E5DyxSbc/g==
      =El++
      -----END PGP MESSAGE-----
    fp: 3AD2C89457C78C2E0D65C5755F12F988B9C91DD7
  encrypted_regex: ^(data|stringData)$
  version: 3.8.1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
  namespace: apps
spec:
  selector:
    matchLabels:
      app: podinfo
  template:
    metadata:
      labels:
        app: podinfo
    spec:
      containers:
        - name: podinfod
          image: ghcr.io/stefanprodan/podinfo:5.2.1 # {"$imagepolicy": "flux-system:podinfo"}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 9898
              protocol: TCP
