apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitlab-auth
  namespace: apps
spec:
  encryptedData:
    password: AgCnS1k5f4z9jv1K8wghx+fvqjN2xRsN8rw1scIsOQQd0umHmfd3jNXSdacCp5Gcb8bys0Li0sufAGsLVZG5W38ugLuFuwwJNcEB/Ehe3Gl6/4nRDRe6gldlqjghdJ5NKtJV13kL6QFQb5wHOiafstnOXTHmnEAgjS6oxoTMjt4eWh5mdf5RYcZOvP8S98Rv1UX2GQ72ViHCyVmgI62IpehFhekn8OhNZiFSkaqkJtE3Rt4lH/oa0MdtEPfiCvptZ8kwNwxCt4aR98VVAk4vTczMfZIoYIlcYvFQbdADFT7uZnP+ECyS1xpFJYp0Kl80qD2P4CFKbodFMYyplpCXkqrP6cUnfEg0+Q59EI3a82YXHPALK1/ThZebU7DvfrRgktPy1jvSk1R6LBWcn3HKp30FHTXf3YwZMxB5xQWXO9/l0cp2pdN967Lp30AI44djCWjRwh5HFghF6PZWr3mol0w9x29LI5/3ghaPDh3j60GG6LVG+oXpRuS+HYkEYi4N6uRJTCaw8gxD1cCQm5qgr3S1Uq6DyYgs4/wOGWsW7jgH1gWJxFA/7p/k82Z5UMPjUzaE8lSQd4e+dCP8gPoyrDduisD/I/y7BqRvqcgjixVbtLG5o0w0FcxOqWWbPG9qft84b851+ICohOJdF2mXzxlkP9aQUJ6zufEevqv8RqgQgTjXl+roBc4K6lMv2ARKYSyMfqYX4UfS9z+A1G16lSKT96XE5U+N91hj7g==
    username: AgBk1VURevytqNsok/XwdOd87OwOG07WECOnErpMaXSw+S7dsQvsG4Ui5a2Lszr9e7/UwRYlabzTu5k+N1svauThhxo5WFqhGIamhwtNMdzsWjd6q3Sr08ftNwIlsc2rb7SGsZhzM81pG+I07rADZ/1nez64QlSEoAS9VS8sn46EKFMEqp26QkYQcpw8EpPwaODzYSYv4XS7Ob0/8qgYlbQRExtnCg4kTmmV45mhJUXPkXjAOcyaCK2qob/RLfjM4d7yOlJ0Cug8GBJrEViRP8hBBGuKugKHg+/OcYImi0l+0QwTEIiEDSbnVqAPyQrOHEU8sN280liZcUb6kPCLYn3X9cnnZVH8k69wuw5i5ldcIGCDEU3LkG3PP3/7BAzd/FofXpk4yA6j6lqROFCPxR44IpDI6IcPL+aPDTAo1Ic0f5/wZtqtrQqnBM9RRjkqtn2Ujvg5jute3DvjAmwHI4RiwHAaGtodkYGjK0RSxO7BSyipgt+XaqmRODK6hlbDnsebIfIFf+pq8zAKB07d+xCPh8TBUdOkoZa64SLtIHcZ2tKX6omSqppwmp7ERrZ+2KNpHR1+y3SQ8F2xcuVW/ldj0QN43KNT0nDkWcJz2OuYOu8640K4yTpu9u774x2iFJsc8ef70sOK8hTitueIPW6xR6Tgc4NY+HE7syB9Nx5FnI4r9g7xBoY4smLo7rOFO3CZiJFlSPZJoLIFnColRKUfqlM=
  template:
    metadata:
      creationTimestamp: null
      name: gitlab-auth
      namespace: apps

