apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dev
  namespace: apps
spec:
  path: ./kustomize/staging
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
